apiVersion: package.appvia.io/v2beta1
kind: Package
metadata:
  name: prometheus
spec:
  installNamespace: prometheus
  name: prometheus
  releaseName: prometheus
  selectors:
    matchExpressions:
    - key: appvia.io/managementcluster
      operator: DoesNotExist
  source:
    helm:
      name: prometheus
      url: https://prometheus-community.github.io/helm-charts
      version: v24.1.0
  summary: prometheus
  values:
    prometheus-pushgateway:
      enabled: false
    alertmanager:
      enabled: false
    extraScrapeConfigs: |
      - job_name: opencost
        honor_labels: true
        scrape_interval: 1m
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        dns_sd_configs:
        - names:
          - opencost.opencost
          type: 'A'
          port: 9003
  valuesFrom:
  version: v24.1.0