apiVersion: package.appvia.io/v2beta1
kind: Package
metadata:
  labels:
    packages.appvia.io/name: external-secrets
  name: external-secrets
spec:
  installNamespace: external-secrets
  name: External Secrets
  releaseName: external-secrets
  selectors:
    matchExpressions:
    - key: appvia.io/managementcluster
      operator: DoesNotExist
    - key: appvia.io/provider
      operator: In
      values:
      - EKS
  source:
    helm:
      name: external-secrets
      url: https://charts.external-secrets.io
      version: v0.8.3
  summary: External secret management for Kubernetes
  values: {}
  valuesFrom:
  - cluster:
      key: spec.cloudResourceName
      path: spec.package.workloadIdentity.providerDetails.aws.customIAMPolicy.Statement.0.Resource.-1
      specPath: true
      valuePrefix: arn:aws:secretsmanager:*:*:secret:wayfinder/
      valueSuffix: /*
  - cluster:
      key: spec.cloudResourceName
      path: spec.package.workloadIdentity.providerDetails.aws.customIAMPolicy.Statement.1.Resource.-1
      specPath: true
      valuePrefix: arn:aws:ssm:*:*:parameter/wayfinder/
      valueSuffix: /*
  version: v0.8.3-17
  workloadIdentity:
    clusterServiceAccount:
      name: external-secrets
      namespace: external-secrets
    providerDetails:
      aws:
        customIAMPolicy:
          Statement:
          - Action:
            - secretsmanager:GetResourcePolicy
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
            - secretsmanager:ListSecretVersionIds
            Effect: Allow
            Resource:
            - arn:aws:secretsmanager:*:*:secret:wayfinder/common/*
          - Action:
            - ssm:GetParameter
            - ssm:ListTagsForResource
            - ssm:DescribeParameters
            Effect: Allow
            Resource:
            - arn:aws:ssm:*:*:parameter/wayfinder/common/*
          Version: "2012-10-17"
        helmServiceAccountAnnotationsPaths:
        - serviceAccount.annotations
    role: None
