apiVersion: compute.appvia.io/v2beta1
kind: ClusterPlan
metadata:
  name: eks-standard
spec:
  summary: General purpose EKS cluster.

  allocation:
    type: all
    workspaces: ["*"]

  template:
    channel: default
    enableAutoUpgrade: false
    enablePrivateCluster: false
    provider: EKS
    providerDetails:
      eks:
        cloudWatchLogging:
          audit: true
      type: EKS
    region: eu-west-2

    clusterLabels:
      appvia.io/ingresspublic: "true"

    security:
      podSecurityStandard:
        enabled: true
        defaultProfile: baseline
        allowed: ["restricted", "baseline", "privileged"]

    networking:
      networkPlan: eks-fixed
      authorizedMasterNetworks:
        - cidr: 0.0.0.0/0
          name: default
      authorizedNetworks:
        - cidr: 0.0.0.0/0
          name: default

    nodePools:
      - logicalName: compute
        image: AL2_x86_64
        diskSize: 30
        autoscaling:
          enabled: true
          maxSize: 10
          minSize: 2
        machine: t3.large
        size: 2

    # See doc/development/quotalimits.md
    quotaLimits:
      default: small
      templates:
      - name: small
        constraints:
          hardQuota:
            "requests.cpu": "512m"
            "requests.memory": "1Gi"
          limitRanges:
          - type: Pod
            max:
              "cpu": "512m"
              "memory": "1024Mi"
              "ephemeral-storage": "4.5Gi"
        resourceDefaults:
        - type: Container
          default:
            "cpu": "512m"
            "memory": "1024Mi"
            "ephemeral-storage": "500Mi"
          defaultRequest:
            "cpu": "50m"
            "memory": "200m"
      - name: medium
        constraints:
          hardQuota:
            "requests.cpu": "1"
            "requests.memory": "2Gi"
          limitRanges:
          - type: Pod
            max:
              "cpu": "256m"
              "memory": "512Mi"
              "ephemeral-storage": "2.25Gi"
        resourceDefaults:
        - type: Container
          default:
            "cpu": "256m"
            "memory": "512Mi"
            "ephemeral-storage": "10Mi"
          defaultRequest:
            "cpu": "50m"
            "memory": "200m"
      - name: large
        constraints:
          hardQuota:
            "requests.cpu": "4Gi"
            "requests.memory": "8Gi"
          limitRanges:
          - type: Pod
            max:
              "cpu": "1"
              "memory": "2Gi"
              "ephemeral-storage": "9Gi"
        resourceDefaults:
        - type: Container
          default:
            "cpu": "1"
            "memory": "2Gi"
            "ephemeral-storage": "1Gi"
          defaultRequest:
            "cpu": "50m"
            "memory": "200Mi"

