apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalClusterPolicy
metadata:
  name: limitranges.default.global
spec:
  policy:
    kyverno:
      validationFailureAction: enforce
      background: false
      rules:
      - name: block-limitranges-changes
        match:
          resources:
            kinds:
            - LimitRange
            - ResourceQuota
        exclude:
          subjects:
          - kind: ServiceAccount
            name: "wf-cluster-admin"
            namespace: "kube-system"
        validate:
          message: "LimitRanges and ResourceQuotas are managed by cluster admins"
          deny:
            conditions:
              any:
                - key: "{{request.operation || 'BACKGROUND'}}"
                  operator: AnyIn
                  value:
                  - DELETE
                  - UPDATE
                  - CREATE
                  - PATCH
    type: Kyverno
