apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalClusterPolicy
metadata:
  name: service.nodeport.global
spec:
  policy:
    kyverno:
      validationFailureAction: enforce
      background: false
      rules:
      - name: validate-nodeport
        match:
          resources:
            kinds:
            - Service
        validate:
          message: "Services of type NodePort are not allowed"
          pattern:
            spec:
              =(type): "!NodePort"
    type: Kyverno
    