apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalClusterPolicy
metadata:
  name: restrict-external-secrets
spec:
  policy:
    kyverno:
      background: false
      rules:
      - exclude:
          resources: {}
        generate:
          clone: {}
          cloneList: {}
        match:
          any:
          - resources:
              kinds:
              - ExternalSecret
          resources: {}
        mutate: {}
        name: check-external-secret-namespace-scoped
        validate:
          foreach:
          - deny:
              conditions:
                all:
                - key: '{{ element.remoteRef.key }}'
                  operator: AnyNotIn
                  value:
                  - wayfinder/common/*
                  - wayfinder/*/{{ request.namespace }}/*
                  - /wayfinder/common/*
                  - /wayfinder/*/{{ request.namespace }}/*
            list: request.object.spec.data[]
          message: ExternalSecrets can only reference AWS Secrets or Parameters that
            are shared, or scoped to your namespace (e.g. 'wayfinder/common/<secretName>',
            'wayfinder/<clusterName>/{{ request.namespace }}/<secretName>', '/wayfinder/common/<parameterName>',
            '/wayfinder/<clusterName>/{{ request.namespace }}/<parameterName>').
      validationFailureAction: enforce
    type: Kyverno
  target:
    cluster: {}
    namespace: {}
