apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalClusterPolicy
metadata:
  annotations:
    defaults.appvia.io/version: v2.3.0-rc1-1692365545
  name: service.nodeport.global
spec:
  policy:
    kyverno:
      background: false
      rules:
      - exclude:
          resources: {}
        generate:
          clone: {}
          cloneList: {}
        match:
          resources:
            kinds:
            - Service
        mutate: {}
        name: validate-nodeport
        validate:
          message: Services of type NodePort are not allowed
          pattern:
            spec:
              =(type): '!NodePort'
      validationFailureAction: enforce
    type: Kyverno
  target:
    cluster: {}
    namespace: {}
