apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalClusterPolicy
metadata:
  annotations:
    defaults.appvia.io/version: v2.3.0-rc1-1692365545
  name: networkpolicy.default.global
spec:
  policy:
    kyverno:
      background: false
      rules:
      - exclude:
          resources: {}
          subjects:
          - kind: ServiceAccount
            name: wf-cluster-admin
            namespace: kube-system
        generate:
          clone: {}
          cloneList: {}
        match:
          resources:
            kinds:
            - NetworkPolicy
            names:
            - default-denial-ingress
        mutate: {}
        name: block-default-policy-changes
        validate:
          deny:
            conditions:
              any:
              - key: '{{request.operation || ''BACKGROUND''}}'
                operator: AnyIn
                value:
                - DELETE
                - UPDATE
                - PATCH
                - CREATE
          message: The default denial NetworkPolicy cannot be deleted
      validationFailureAction: enforce
    type: Kyverno
  target:
    cluster: {}
    namespace: {}
