apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalClusterPolicy
metadata:
  name: bp-disallow-default-namespace
spec:
  policy:
    type: Kyverno
    kyverno:
      validationFailureAction: enforce
      background: false
      rules:
      - name: bp-disallow-default-namespace
        match:
          any:
          - resources:
              kinds:
              - DaemonSet
              - Deployment
              - Job
              - StatefulSet
              - Pod
        validate:
          message: "Using 'default' namespace is not allowed for pod controllers."
          pattern:
            metadata:
              namespace: "!default"