apiVersion: package.appvia.io/v2beta1
kind: Repository
metadata:
  name: splunk-otel-collector
spec:
  interval: 60m
  selectors:
    matchExpressions:
    - key: appvia.io/managementcluster
      operator: DoesNotExist
    - key: appvia.io/provider
      operator: In
      values:
      - AKS
  timeout: 60s
  url: https://signalfx.github.io/splunk-otel-collector-chart