apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalClusterPolicy
metadata:
  name: flux.default.global
spec:
  policy:
    kyverno:
      validationFailureAction: enforce
      background: false
      rules:
      - name: validate-helmrelease-serviceaccount
        match:
          resources:
            kinds:
            - HelmRelease
            namespaceSelector:
              matchExpressions:
                - key: appvia.io/workspace
                  operator: Exists
        exclude:
          subjects:
          - kind: ServiceAccount
            namespace: kube-system
            name: "wf-cluster-admin"
        validate:
          message: "HelmReleases must specify a ServiceAccount"
          pattern:
            spec:
              serviceAccountName: "?*"
    type: Kyverno
