apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalClusterPolicy
metadata:
  name: networkpolicy.default.global
spec:
  policy:
    kyverno:
      validationFailureAction: enforce
      background: false
      rules:
      - name: block-default-policy-changes
        match:
          resources:
            kinds:
            - NetworkPolicy
            names:
            - default-denial-ingress
        exclude:
          subjects:
          - kind: ServiceAccount
            name: "wf-cluster-admin"
            namespace: "kube-system"
        validate:
          message: "The default denial NetworkPolicy cannot be deleted"
          deny:
            conditions:
              any:
                - key: "{{request.operation || 'BACKGROUND'}}"
                  operator: AnyIn
                  value:
                  - DELETE
                  - UPDATE
                  - PATCH
                  - CREATE
    type: Kyverno
