apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalClusterPolicy
metadata:
  name: pvc.storageclass.global
spec:
  policy:
    kyverno:
      validationFailureAction: enforce
      background: false
      rules:
      - name: block-manual-pvc-storageclass
        match:
          resources:
            kinds:
            - PersistentVolumeClaim
        exclude:
          subjects:
          - kind: ServiceAccount
            namespace: wf-manager
            name: "helm-controller"
        validate:
          message: "PersistentVolumeClaims may not use the manual storage class"
          pattern:
            spec:
              =(storageClassName): "!manual"
      - name: block-manual-statefulset-storageclass
        match:
          resources:
            kinds:
            - StatefulSet
        exclude:
          subjects:
          - kind: ServiceAccount
            namespace: wf-manager
            name: "helm-controller"
        validate:
          message: "StatefulSets may not use the manual storage class"
          pattern:
            spec:
              =(volumeClaimTemplates):
              - spec:
                  =(storageClassName): "!manual"
    type: Kyverno
