apiVersion: package.appvia.io/v2beta1
kind: Repository
metadata:
  name: external-secrets
spec:
  interval: 60m
  selectors:
    matchExpressions:
    - key: appvia.io/provider
      operator: In
      values:
      - EKS
  timeout: 60s
  url: https://charts.external-secrets.io
