apiVersion: package.appvia.io/v2beta1
kind: Repository
metadata:
  name: keda
spec:
  interval: 60m
  selectors:
    matchExpressions:
    - key: appvia.io/managementcluster
      operator: DoesNotExist
    - key: appvia.io/provider
      operator: In
      values:
      - EKS
  timeout: 60s
  url: https://kedacore.github.io/charts
