apiVersion: org.appvia.io/v2beta1
kind: WayfinderRoleBinding
metadata:
  annotations:
    defaults.appvia.io/version: v2.3.0-rc1-1692365545
  name: workspacecreator
spec:
  roleRef:
    kind: WayfinderRole
    name: workspacecreator
  subjects:
  - kind: WayfinderGroup
    name: authenticated
