apiVersion: compute.appvia.io/v2beta1
kind: ClusterPlan
metadata:
  name: eks-secure-fixed-zones
spec:
  allocation:
    type: all
  policies:
  - editable: false
    path: spec.region
  - editable: false
    path: spec.version
  - editable: false
    path: spec.expires
  - editable: false
    path: spec.enablePrivateCluster
  - editable: false
    path: spec.providerDetails.eks.cloudWatchLogging.api
  - editable: false
    path: spec.providerDetails.eks.cloudWatchLogging.authenticator
  - editable: false
    path: spec.providerDetails.eks.cloudWatchLogging.controllerManager
  - editable: false
    path: spec.providerDetails.eks.cloudWatchLogging.audit
  - editable: false
    path: spec.providerDetails.eks.cloudWatchLogging.scheduler
  - editable: true
    path: spec.enableAutoUpgrade
  - editable: false
    path: spec.networking.authorizedNetworks
  - editable: false
    path: spec.networking.authorizedMasterNetworks
  summary: Private EKS Cluster, locked to VPN
  template:
    enableAutoUpgrade: false
    enablePrivateCluster: true
    networking:
      authorizedMasterNetworks:
      - cidr: 0.0.0.0/0
        name: default
      authorizedNetworks:
      - cidr: 10.32.0.0/16
        name: default
      networkPlan: eks-standard-fixed-azs
    nodePools:
    - autoscaling:
        enabled: true
        maxSize: 10
        minSize: 2
      diskSize: 30
      image: AL2_x86_64
      logicalName: compute
      machine: t3.large
      size: 2
    provider: EKS
    providerDetails:
      eks:
        cloudWatchLogging: {}
      type: EKS
    quotaLimits:
      default: small
      templates:
      - constraints:
          hardQuota:
            requests.cpu: "1"
            requests.memory: 2Gi
          limitRanges:
          - max:
              cpu: 256m
              ephemeral-storage: 2.25Gi
              memory: 512Mi
            type: Pod
        name: small
        resourceDefaults:
        - default:
            cpu: 256m
            ephemeral-storage: 10Mi
            memory: 512Mi
          defaultRequest:
            cpu: 50m
            memory: 200m
          type: Container
      - constraints:
          hardQuota:
            requests.cpu: 512m
            requests.memory: 1Gi
          limitRanges:
          - max:
              cpu: 512m
              ephemeral-storage: 4.5Gi
              memory: 1024Mi
            type: Pod
        name: medium
        resourceDefaults:
        - default:
            cpu: 512m
            ephemeral-storage: 500Mi
            memory: 1024Mi
          defaultRequest:
            cpu: 50m
            memory: 200m
          type: Container
      - constraints:
          hardQuota:
            requests.cpu: 4Gi
            requests.memory: 8Gi
          limitRanges:
          - max:
              cpu: "1"
              ephemeral-storage: 9Gi
              memory: 2Gi
            type: Pod
        name: large
        resourceDefaults:
        - default:
            cpu: "1"
            ephemeral-storage: 1Gi
            memory: 2Gi
          defaultRequest:
            cpu: 50m
            memory: 200Mi
          type: Container
    region: us-east-1
    security:
      podSecurityStandard:
        allowed:
        - restricted
        - baseline
        - privileged
        defaultProfile: baseline
        enabled: true
    version: 1.24.8
