apiVersion: cloudresources.appvia.io/v2beta1
kind: CloudResourcePlan
metadata:
  annotations:
    appvia.io/source: azurerm-demo-storage-account
  name: azurerm-demo-storage-account
spec:
  allocation:
    type: all
  cloud: azure
  description: Imported from https://github.com/Digital-Garage-ICL/terraform-azurerm-demo-storage-account
  enableTemplateAutoUpgrade: false
  enableWatch: false
  inputDefinitions:
  - default: null
    description: Allow or disallow public access to all blobs or containers in the
      storage account.
    name: allow_nested_items_to_be_public
    type: bool
  - default: null
    description: Map of CIDRs Storage Account access.
    name: access_list
    type: map(string)
  - default: null
    description: Indicates whether the storage account permits requests to be authorized
      with the account access key via Shared Key
    name: shared_access_key_enabled
    type: bool
  - default: null
    description: Enable Hierarchical Namespace (can be used with Azure Data Lake Storage
      Gen 2).
    name: enable_hns
    type: bool
  - default: null
    description: Retention days for deleted container. Valid value is between 1 and
      365 (set to 0 to disable).
    name: container_delete_retention_days
    type: number
  - default: null
    description: tags to be applied to resources
    name: tags
    required: true
    type: map(string)
  - default: null
    description: Defines the Tier to use for this storage account (Standard or Premium).
    name: account_tier
    type: string
  - default: null
    description: Defines the access tier for BlobStorage, FileStorage and StorageV2
      accounts
    name: access_tier
    type: string
  - default: null
    description: Specifies whether traffic is bypassed for Logging/Metrics/AzureServices.
      Valid options are any combination of Logging, Metrics, AzureServices, or None.
    name: traffic_bypass
    type: list(string)
  - default: null
    description: Controls if static website to be enabled on the storage account.
      Possible values are `true` or `false`
    name: enable_static_website
    type: bool
  - default: null
    description: Controls whether blob object versioning is enabled.
    name: blob_versioning_enabled
    type: bool
  - default: null
    description: container access type
    name: container_access_type
    type: string
  - default: null
    description: Specifies the supported Azure location to MySQL server resource
    name: location
    required: true
    type: string
  - default: null
    description: Storage account replication type - i.e. LRS, GRS, RAGRS, ZRS, GZRS,
      RAGZRS.
    name: replication_type
    required: true
    type: string
  - default: null
    description: Creates a virtual network rule in the subnet_id (values are virtual
      network subnet ids).
    name: service_endpoints
    type: map(string)
  - default: null
    description: Retention days for deleted blob. Valid value is between 1 and 365
      (set to 0 to disable).
    name: blob_delete_retention_days
    type: number
  - default: null
    description: Storage account name
    name: name
    type: string
  - default: null
    description: name of the resource group to create the resource
    name: resource_group_name
    required: true
    type: string
  - default: null
    description: Enable Large File Share.
    name: enable_large_file_share
    type: bool
  - default: null
    description: path from your repo root to index.html
    name: index_path
    type: string
  - default: null
    description: Enable SFTP for storage account (enable_hns must be set to true for
      this to work).
    name: enable_sftp
    type: bool
  - default: null
    description: The minimum supported TLS version for the storage account.
    name: min_tls_version
    type: string
  - default: null
    description: path from your repo root to your custom 404 page
    name: custom_404_path
    type: string
  - default: null
    description: Defines the Kind of account. Valid options are BlobStorage, BlockBlobStorage,
      FileStorage, Storage and StorageV2
    name: account_kind
    type: string
  - default: null
    description: Forces HTTPS if enabled.
    name: enable_https_traffic_only
    type: bool
  - default: null
    description: Specifies the default action of allow or deny when no other network
      rules match
    name: default_network_rule
    type: string
  - default: null
    description: Storage account name
    name: container_name
    required: true
    type: string
  - default: null
    description: 'blob service cors rules:  https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#cors_rule'
    name: blob_cors
    type: |-
      map(object({
          allowed_headers    = list(string)
          allowed_methods    = list(string)
          allowed_origins    = list(string)
          exposed_headers    = list(string)
          max_age_in_seconds = number
        }))
  - default: null
    description: Is infrastructure encryption enabled? Changing this forces a new
      resource to be created.
    name: infrastructure_encryption_enabled
    type: bool
  - default: null
    description: Is NFSv3 protocol enabled? Changing this forces a new resource to
      be created
    name: nfsv3_enabled
    type: bool
  outputs:
  - description: Hostname with port for web storage in the secondary location.
    name: secondary_web_host
  - description: The Tenant ID for the Service Principal associated with the Identity
      of this Storage Account.
    name: tenant_id
  - description: The endpoint URL for table storage in the secondary location.
    name: secondary_table_endpoint
  - description: The secondary access key for the storage account.
    name: secondary_access_key
    sensitive: true
  - description: The endpoint host for blob storage in the secondary location.
    name: secondary_blob_host
  - description: The endpoint URL for table storage in the primary location.
    name: primary_table_endpoint
  - description: The name of the Storage Account container.
    name: container_name
  - description: The endpoint URL for web storage in the secondary location.
    name: secondary_web_endpoint
  - description: The connection string associated with the primary blob location.
    name: primary_blob_connection_string
    sensitive: true
  - description: The endpoint URL for file storage in the secondary location.
    name: secondary_file_endpoint
  - description: The connection string associated with the secondary location.
    name: secondary_connection_string
    sensitive: true
  - description: The ID of the Storage Account.
    name: id
  - description: The endpoint URL for blob storage in the primary location.
    name: primary_blob_endpoint
  - description: The endpoint host for blob storage in the primary location.
    name: primary_blob_host
  - description: The primary access key for the storage account.
    name: primary_access_key
    sensitive: true
  - description: The endpoint URL for queue storage in the secondary location.
    name: secondary_queue_endpoint
  - description: The connection string associated with the primary location.
    name: primary_connection_string
    sensitive: true
  - description: Hostname with port for web storage in the primary location.
    name: primary_web_host
  - description: The connection string associated with the secondary blob location.
    name: secondary_blob_connection_string
    sensitive: true
  - description: The name of the Storage Account.
    name: name
  - description: The endpoint URL for queue storage in the primary location.
    name: primary_queue_endpoint
  - description: The endpoint URL for DFS storage in the primary location.
    name: primary_dfs_endpoint
  - description: The endpoint URL for DFS storage in the secondary location.
    name: secondary_dfs_endpoint
  - description: The endpoint URL for web storage in the primary location.
    name: primary_web_endpoint
  - description: The Principal ID for the Service Principal associated with the Identity
      of this Storage Account.
    name: principal_id
  - description: The Storage Account object.
    name: sa
    sensitive: true
  - description: The endpoint URL for blob storage in the secondary location.
    name: secondary_blob_endpoint
  - description: The endpoint URL for file storage in the primary location.
    name: primary_file_endpoint
  policies:
  - editable: false
    path: allow_nested_items_to_be_public
  - editable: false
    path: access_list
  - editable: false
    path: shared_access_key_enabled
  - editable: false
    path: enable_hns
  - editable: false
    path: container_delete_retention_days
  - editable: false
    path: tags
  - editable: false
    path: account_tier
  - editable: false
    path: access_tier
  - editable: false
    path: traffic_bypass
  - editable: false
    path: enable_static_website
  - editable: false
    path: blob_versioning_enabled
  - editable: false
    path: container_access_type
  - editable: false
    path: location
  - editable: false
    path: replication_type
  - editable: false
    path: service_endpoints
  - editable: false
    path: blob_delete_retention_days
  - editable: true
    path: name
  - editable: true
    path: resource_group_name
  - editable: false
    path: enable_large_file_share
  - editable: false
    path: index_path
  - editable: false
    path: enable_sftp
  - editable: false
    path: min_tls_version
  - editable: false
    path: custom_404_path
  - editable: false
    path: account_kind
  - editable: false
    path: enable_https_traffic_only
  - editable: false
    path: default_network_rule
  - editable: true
    path: container_name
  - editable: false
    path: blob_cors
  - editable: false
    path: infrastructure_encryption_enabled
  - editable: false
    path: nfsv3_enabled
  template:
    revision: v1.0.5
    source: https://github.com/Digital-Garage-ICL/terraform-azurerm-demo-storage-account
    variables:
      container_name: demostorageaccountcontainer
      default_network_rule: Allow
      location: uksouth
      replication_type: LRS
      resource_group_name: wf-ws-app-aks-abfek-infra-uksouth
      shared_access_key_enabled: true
      tags:
        name: demo-storage-account