---
apiVersion: compute.appvia.io/v2beta1
kind: ClusterPlan
metadata:
  name: eks-appvia-private
spec:
  allocation:
    type: all
  policies:
    - editable: false
      path: spec.region
    - editable: false
      path: spec.version
    - editable: false
      path: spec.expires
    - editable: false
      path: spec.enablePrivateCluster
    - editable: false
      path: spec.providerDetails.eks.cloudWatchLogging.api
    - editable: false
      path: spec.providerDetails.eks.cloudWatchLogging.authenticator
    - editable: false
      path: spec.providerDetails.eks.cloudWatchLogging.controllerManager
    - editable: false
      path: spec.providerDetails.eks.cloudWatchLogging.audit
    - editable: false
      path: spec.providerDetails.eks.cloudWatchLogging.scheduler
    - editable: true
      path: spec.enableAutoUpgrade
    - editable: false
      path: spec.networking.authorizedNetworks
    - editable: false
      path: spec.networking.authorizedMasterNetworks
    - editable: false
      path: spec.networking.networkPlan
    - editable: false
      path: spec.security
  summary: Private EKS Cluster, only accessible via Appvia VPN
  template:
    clusterLabels:
      appvia.io/ingresspublic: "true"
      appvia.io/ingressinternal: "true"
    enableAutoUpgrade: false
    enablePrivateCluster: true
    networking:
      networkPlan: eks-appvia
      authorizedMasterNetworks:
        - cidr: 0.0.0.0/0
          name: default
      authorizedNetworks:
        - cidr: 10.0.1.0/24
          name: vpn
        - cidr: 10.0.2.0/24
          name: github-runners
    nodePools:
      - autoscaling:
          enabled: true
          maxSize: 10
          minSize: 2
        diskSize: 30
        image: AL2_x86_64
        logicalName: compute
        machine: t3.large
        size: 2
    provider: EKS
    providerDetails:
      eks:
        cloudWatchLogging:
          api: true
          audit: true
          authenticator: true
          controllerManager: true
          scheduler: true
      type: EKS
    quotaLimits:
      default: small
      templates:
        - name: small
          constraints:
            hardQuota:
              requests.cpu: 512m
              requests.memory: 1Gi
            limitRanges:
              - max:
                  cpu: 256m
                  ephemeral-storage: 2.25Gi
                  memory: 512Mi
                type: Pod
          resourceDefaults:
            - default:
                cpu: 256m
                ephemeral-storage: 10Mi
                memory: 512Mi
              defaultRequest:
                cpu: 50m
                memory: 200m
              type: Container
        - name: medium
          constraints:
            hardQuota:
              requests.cpu: "1"
              requests.memory: 2Gi
            limitRanges:
              - max:
                  cpu: 512m
                  ephemeral-storage: 4.5Gi
                  memory: 1024Mi
                type: Pod
          resourceDefaults:
            - default:
                cpu: 512m
                ephemeral-storage: 500Mi
                memory: 1024Mi
              defaultRequest:
                cpu: 50m
                memory: 200m
              type: Container
        - name: large
          constraints:
            hardQuota:
              requests.cpu: 4Gi
              requests.memory: 8Gi
            limitRanges:
              - max:
                  cpu: "1"
                  ephemeral-storage: 9Gi
                  memory: 2Gi
                type: Pod
          resourceDefaults:
            - default:
                cpu: "1"
                ephemeral-storage: 1Gi
                memory: 2Gi
              defaultRequest:
                cpu: 50m
                memory: 200Mi
              type: Container
    region: eu-west-2
    security:
      podSecurityStandard:
        allowed:
          - restricted
          - baseline
          - privileged
        defaultProfile: baseline
        enabled: true
    version: "1.25"
