apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalAccessPolicy
metadata:
  name: secretsviewer.nonprod
spec:
  accessPolicyTemplate:
    description: Secrets read access to non-production clusters
    accessRoleRefs: [ "secrets.view" ]
    groups: [ "secretsviewer-nonprod" ]
    subjectType: User
    constraints:
      ttl: 8h00m0s
      clusters:
        allowed:
          matchLabels:
            "appvia.io/stage": "nonprod"
