apiVersion: policydelivery.appvia.io/v1alpha1
kind: ClusterPolicy
metadata:
  name: cluster.deployment
  namespace: ws-amir
spec:
  policy:
    kuberbac:
      clusterScoped: true
      rules:
      - apiGroups:
        - ""
        - policy
        - rbac.authorization.k8s.io
        resources:
        - clusterrolebindings
        - clusterroles
        - namespaces
        - nodes
        - podsecuritypolicies
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - cert-manager.io
        resources:
        - '*'
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - ""
        resources:
        - configmaps
        - endpoints
        - events
        - persistentvolumeclaims
        - persistentvolumes
        - pods
        - secrets
        - serviceaccounts
        - services
        verbs:
        - '*'
      - apiGroups:
        - apps
        - batch
        - coordination.k8s.io
        - extensions
        - networking.k8s.io
        resources:
        - cronjobs
        - deployments
        - deployments/rollback
        - deployments/scale
        - frontendconfigs
        - ingressclasses
        - ingresses
        - jobs
        - networkpolicies
        - replicasets
        - replicasets/scale
        - replicationcontrollers/scale
        - statefulsets
        - statefulsets/scale
        verbs:
        - '*'
      - apiGroups:
        - policy
        resources:
        - poddisruptionbudgets
        verbs:
        - '*'
      - apiGroups:
        - rbac.authorization.k8s.io
        resources:
        - roles
        - rolebindings
        verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
      - apiGroups:
        - autoscaling
        resources:
        - horizontalpodautoscalers
        - verticalpodautoscalers
        verbs:
        - '*'
      - apiGroups:
        - acme.cert-manager.io
        - cert-manager.io
        - helm.toolkit.fluxcd.io
        - source.toolkit.fluxcd.io
        resources:
        - '*'
        verbs:
        - '*'
      - apiGroups:
        - terraform.appvia.io
        resources:
        - configurations
        verbs:
        - '*'
    type: KubeRBAC
  target:
    cluster: {}
    namespace:
      matchLabels:
        appvia.io/workspace: amir
