apiVersion: policydelivery.appvia.io/v1alpha1
kind: ClusterPolicy
metadata:
  name: secrets.view
  namespace: ws-amir
spec:
  policy:
    kuberbac:
      rules:
      - apiGroups:
        - ""
        resources:
        - secrets
        verbs:
        - get
        - list
        - watch
    type: KubeRBAC
  target:
    cluster: {}
    namespace:
      matchLabels:
        appvia.io/workspace: amir
