apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalAccessRole
metadata:
  name: cluster.admin
spec:
  accessRoleTemplate:
    description: Full cluster administration
    clusterScope: true
    rules:
    - verbs:
      - '*'
      apiGroups:
      - '*'
      - '*/*'
      resources:
      - '*'



