apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalAccessPolicy
metadata:
  name: admin.nonprod
spec:
  accessPolicyTemplate:
    description: Admin access to non-production clusters
    accessRoleRefs: [ "cluster.admin", "namespace.admin" ]
    wayfinderGroups: [ "admin" ]
    groups: [ "owner" ]
    subjectType: User
    constraints:
      ttl: 8h00m0s
      clusters:
        allowed:
          matchLabels:
            "appvia.io/stage": "nonprod"
