apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalAccessRole
metadata:
  name: secrets.view
spec:
  accessRoleTemplate:
    description: View secrets
    clusterScope: false
    rules:
    # Read-only access to just secrets:
    - verbs:
      - 'get'
      - 'list'
      - 'watch'
      apiGroups:
      - ''
      resources:
      - 'secrets'
