apiVersion: policydelivery.appvia.io/v1alpha1
kind: ClusterPolicy
metadata:
  name: cluster.deployment-readonly
  namespace: ws-amir
spec:
  policy:
    kuberbac:
      clusterScoped: true
      rules:
      - apiGroups:
        - ""
        - policy
        - rbac.authorization.k8s.io
        resources:
        - clusterrolebindings
        - clusterroles
        - namespaces
        - nodes
        - podsecuritypolicies
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - cert-manager.io
        resources:
        - '*'
        verbs:
        - get
        - list
        - watch
    type: KubeRBAC
  target:
    cluster: {}
    namespace:
      matchLabels:
        appvia.io/workspace: amir
