apiVersion: policydelivery.appvia.io/v1alpha1
kind: ClusterPolicy
metadata:
  name: cluster.view
  namespace: ws-amir
spec:
  policy:
    kuberbac:
      clusterScoped: true
      rules:
      - apiGroups:
        - ""
        resources:
        - bindings
        - configmaps
        - endpoints
        - events
        - limitranges
        - persistentvolumeclaims
        - pods
        - pods/log
        - podtemplates
        - replicationcontrollers
        - resourcequotas
        - serviceaccounts
        - services
        - componentstatuses
        - namespaces
        - nodes
        - persistentvolumes
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - apps
        - batch
        - autoscaling
        - networking.k8s.io
        - authentication.k8s.io
        - authorization.k8s.io
        - rbac.authorization.k8s.io
        - cert-manager.io
        - helm.toolkit.fluxcd.io
        - source.toolkit.fluxcd.io
        - aadpodidentity.k8s.io
        - admissionregistration.k8s.io
        - apiextensions.k8s.io
        resources:
        - '*'
        verbs:
        - get
        - list
        - watch
    type: KubeRBAC
  target:
    cluster: {}
    namespace:
      matchLabels:
        appvia.io/workspace: amir
