apiVersion: networking.appvia.io/v2beta1
kind: ClusterNetworkPlan
metadata:
  name: eks-assignable
spec:
  summary: General purpose EKS cluster network using assignable IP ranges

  assignableNetworks:
  - aws-nonprod
  - aws-prod

  template:
    plan: eks-assignable
    provider: aws
    providerDetails:
      type: aws
      aws:
        availabilityZones: 3
        NatGateways: 3
    ipv4:
      cidrBlocks:
      - type: node
        size: 24
    layout:
      mode: auto
      privateSubnets: 3
      publicSubnets: 3
